// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Q_OhYPDeRpFWPRe-qURjalWdv8XjrGk',
    appId: '1:756816975393:web:d97d9afbe9896dc2b8b560',
    messagingSenderId: '756816975393',
    projectId: 'flutter-samples-63251',
    authDomain: 'flutter-samples-63251.firebaseapp.com',
    storageBucket: 'flutter-samples-63251.appspot.com',
    measurementId: 'G-XQYX0GQWNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1-q14imNxV82O91zIbKqFgDyQG5MVBA',
    appId: '1:756816975393:android:0671f57ac5cdddc4b8b560',
    messagingSenderId: '756816975393',
    projectId: 'flutter-samples-63251',
    storageBucket: 'flutter-samples-63251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoyTS_qMHooyYABWVPGneFYrRNanj7TEs',
    appId: '1:756816975393:ios:e342f5787f2acc4cb8b560',
    messagingSenderId: '756816975393',
    projectId: 'flutter-samples-63251',
    storageBucket: 'flutter-samples-63251.appspot.com',
    androidClientId: '756816975393-omkkhernbos8bj4domlrl31b4765424a.apps.googleusercontent.com',
    iosClientId: '756816975393-sn1kgh726ka4r97ogm3tr6j9b16g2fjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSkeletonTemplate',
  );
}
